name: Patch

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: version to patch (vX.X)
        required: true

jobs:
  run-patch:
    uses: powsybl/github-ci/.github/workflows/patch-backend-app-generic.yml@c81718897ef649fcdc685955a094bf724bf7fa9e
    with:
      githubappId: ${{ vars.GRIDSUITE_ACTIONS_APPID }}
      dockerImage: docker.io/gridsuite/study-server
      dockerUsername: gridsuiteci
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
    secrets:
      VERSIONBUMP_GHAPP_PRIVATE_KEY: ${{ secrets.VERSIONBUMP_GHAPP_PRIVATE_KEY }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

